# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocloud < Formula
  desc "Kick-start any cloud native project in your favourite programming language"
  homepage "https://github.com/ksrichard/gocloud"
  version "0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ksrichard/gocloud/releases/download/0.2/gocloud_0.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "0624940e53bc8410668cce745f183a87711601ac82e557f651567b98a5949e0f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ksrichard/gocloud/releases/download/0.2/gocloud_0.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "1d4d523a4099d5947df8307c5199c324ff58fe95759b1dd54d78e7f81da94138"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gocloud/releases/download/0.2/gocloud_0.2_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
    sha256 "6f3942ad0e33a4bcd51d10b0ebfb002f7b1b62761f2c7fdf899d076e856b453d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gocloud/releases/download/0.2/gocloud_0.2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "5b1fd6064d62b8296507f1f67275b310a3bc20b04c5a448dbb7c1d889ec3b989"
  end

  def install
    bin.install "gocloud"
  end

  def caveats; <<~EOS
    Kick-start any cloud native project in your favourite programming language
  EOS
  end
end
