# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocloud < Formula
  desc "Kick-start any cloud native project in your favourite programming language"
  homepage "https://github.com/ksrichard/gocloud"
  version "0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ksrichard/gocloud/releases/download/0.1/gocloud_0.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "92af67362da4d0b525a4624e627a3f57178022e40e6af7f2ac28c3b160735c5e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ksrichard/gocloud/releases/download/0.1/gocloud_0.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "381f5ae7938b0869bf794ede4d896777be2ce29fcda20fbe1654375b852a9290"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gocloud/releases/download/0.1/gocloud_0.1_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
    sha256 "24942c6b85dfc1a335f5659e397a8086b951bf83512f7ca0b1b90565749dcac5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gocloud/releases/download/0.1/gocloud_0.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "4ca0d1898195e9f733870d14873c5073fa0c8b844730af4857e8ea49858f6075"
  end

  def install
    bin.install "gocloud"
  end

  def caveats; <<~EOS
    Kick-start any cloud native project in your favourite programming language
  EOS
  end
end
