# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogen < Formula
  desc "Simple yet powerful dynamic project generation"
  homepage "https://github.com/ksrichard/gogen"
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ksrichard/gogen/releases/download/0.1/gogen_0.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "7a990fa9577e3cae2daf25f7e5c25e1a752ba70614e14f7f38ae24b56cf7da7b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ksrichard/gogen/releases/download/0.1/gogen_0.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "1127d9fd199919ae241ffcd78104378fcbaec7c9af047f0893b96708e7b1c061"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gogen/releases/download/0.1/gogen_0.1_Linux_armv6.tar.gz", :using => CurlDownloadStrategy.
    sha256 "7a54ad76f31b9d0be553bd5498b98013e5f749a3d586a49151a38a7518d4c331"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gogen/releases/download/0.1/gogen_0.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "497e74b95a9e70f458cce912211c8d99e2f29faffb8fc22f7d171adbc6f8a209"
  end

  def install
    bin.install "gogen"
  end

  def caveats; <<~EOS
    ./gogen generate --help Generating projects/folder structures based on a template
    Usage: gogen generate [flags]
    Flags: -h, --help                  help for generate -o, --output-dir string     Output folder where result files will be generated -t, --template-dir string   Template folder to be used for generation -v, --vars stringToString   Variables for generation (default [])
  EOS
  end
end
