# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogen < Formula
  desc "Simple yet powerful dynamic project generation"
  homepage "https://github.com/ksrichard/gogen"
  version "0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ksrichard/gogen/releases/download/0.2/gogen_0.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "e6ab952497651df331d6341cd6f26033090afac176302c195c1c93f5aa84f6bb"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ksrichard/gogen/releases/download/0.2/gogen_0.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "00de22c05af88f8d11a53d69060043dad736ef5f24aed21bdeac06f9e27f4a35"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gogen/releases/download/0.2/gogen_0.2_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
    sha256 "6d174c35b8660e7bed47c8159c48e26717deac1da02d464d208ef6ae593b271b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/ksrichard/gogen/releases/download/0.2/gogen_0.2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "2c322902b4d446c08409832139c69d1e5272d164d267ebb9f5d51aab04e36c89"
  end

  def install
    bin.install "gogen"
  end

  def caveats; <<~EOS
    ./gogen generate --help Generating projects/folder structures based on a template
    Usage: gogen generate [flags]
    Flags: -h, --help                  help for generate -o, --output-dir string     Output folder where result files will be generated -t, --template-dir string   Template folder to be used for generation -v, --vars stringToString   Variables for generation (default [])
  EOS
  end
end
